### ISSUE TITLE
MigrateController: Error with Tarantool 2.10.4

### ISSUE THREAD

**Issue by arkhamvm** [mhthnz/yii2-tarantool#2]
tarantool 2.8.2:
```
$ ./yii tarantool-migrate
Yii Migration Tool (based on Yii v2.0.44-dev)

No new migrations found. Your system is up-to-date.
```

tarantool 2.10.4:
```
$ ./yii tarantool-migrate
Yii Migration Tool (based on Yii v2.0.44-dev)

Exception 'Exception' with message 'At line 1 at or near position 63: keyword 'table' is reserved. Please use double quotes if 'table' is an identifier.
Failed to prepare SQL: select "format", "id", "engine" from "_space" where "name" = :table'

in /var/www/project/vendor/mhthnz/yii2-tarantool/src/Command.php:231

Caused by: Exception 'Tarantool\Client\Exception\RequestFailed' with message 'At line 1 at or near position 63: keyword 'table' is reserved. Please use double quotes if 'table' is an identifier.'

in /var/www/project/vendor/tarantool/client/src/Exception/RequestFailed.php:32

Stack trace:
#0 /var/www/project/vendor/tarantool/client/src/Handler/DefaultHandler.php(48): Tarantool\Client\Exception\RequestFailed::fromErrorResponse()
#1 /var/www/project/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(63): Tarantool\Client\Handler\DefaultHandler->handle()
#2 /var/www/project/vendor/mhthnz/yii2-tarantool/src/LastInsertIDMiddleware.php(43): Tarantool\Client\Handler\MiddlewareHandler->handle()
#3 /var/www/project/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(69): mhthnz\tarantool\LastInsertIDMiddleware->process()
#4 /var/www/project/vendor/tarantool/client/src/Middleware/AuthenticationMiddleware.php(41): Tarantool\Client\Handler\MiddlewareHandler->handle()
#5 /var/www/project/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(69): Tarantool\Client\Middleware\AuthenticationMiddleware->process()
#6 /var/www/project/vendor/tarantool/client/src/Middleware/RetryMiddleware.php(75): Tarantool\Client\Handler\MiddlewareHandler->handle()
#7 /var/www/project/vendor/tarantool/client/src/Handler/MiddlewareHandler.php(69): Tarantool\Client\Middleware\RetryMiddleware->process()
#8 /var/www/project/vendor/tarantool/client/src/Client.php(221): Tarantool\Client\Handler\MiddlewareHandler->handle()
#9 /var/www/project/vendor/mhthnz/yii2-tarantool/src/Client.php(218): Tarantool\Client\Client->prepare()
#10 /var/www/project/vendor/mhthnz/yii2-tarantool/src/Command.php(228): mhthnz\tarantool\Client->__call()
#11 /var/www/project/vendor/mhthnz/yii2-tarantool/src/Command.php(297): mhthnz\tarantool\Command->prepare()
#12 /var/www/project/vendor/mhthnz/yii2-tarantool/src/Command.php(73): mhthnz\tarantool\Command->queryInternal()
#13 /var/www/project/vendor/mhthnz/yii2-tarantool/src/Schema.php(148): mhthnz\tarantool\Command->queryOne()
#14 /var/www/project/vendor/yiisoft/yii2/db/Schema.php(758): mhthnz\tarantool\Schema->loadTableSchema()
#15 /var/www/project/vendor/mhthnz/yii2-tarantool/src/Schema.php(596): yii\db\Schema->getTableMetadata()
#16 /var/www/project/vendor/mhthnz/yii2-tarantool/src/console/MigrateController.php(114): mhthnz\tarantool\Schema->getTableSchema()
#17 /var/www/project/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(908): mhthnz\tarantool\console\MigrateController->getMigrationHistory()
#18 /var/www/project/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(183): yii\console\controllers\BaseMigrateController->getNewMigrations()
#19 [internal function]: yii\console\controllers\BaseMigrateController->actionUp()
```

**Comment by mhthnz** [comment]
currently i'm not actively maintain this project. i'll fix it as soon as i have free time. other way you can suggest your fixes as pull request

**Comment by arkhamvm** [comment]
I'll try. I hope I can help in some way.

**Comment by mhthnz** [comment]
Looks like we need to change :table placeholder to something else

**Comment by arkhamvm** [comment]
@mhthnz 

https://github.com/mhthnz/yii2-tarantool/blob/1e1000251dd63ad3a3d66f25b172fc3174a90c88/src/session/Session.php#L106

Is this line really works? When I tried it with AR, I got error that PK column value can not be modified (Tarantool 2.10)
